export type Track = { id:string; title:string; feeling:string; feelingKo:string; fit:string; fitKo:string; mood:string; color:string; reference:string; referenceUrl:string; audio:string|null; art:string|null };
export const tracks: Track[] = [
  {
    "id": "bon-appetit",
    "title": "Bon Appétit",
    "feeling": "An upbeat pop-R&B love song that plays with the idea of serving up something spicy.",
    "feelingKo": "매콤한 음식을 차려내듯 설레는 사랑 이야기를 풀어가는 경쾌한 팝 R&B 곡이에요.",
    "fit": "More of a pop-R&B angle, with Dua Lipa vibes. The food analogy is a fun part of it too.",
    "fitKo": "Dua Lipa가 떠오르는 팝 R&B 느낌이에요. 음식에 빗대어 이야기하는 점도 재미있고요.",
    "mood": "POP R&B / 팝 R&B",
    "color": "#f7ea69",
    "audio": "/private/mio-pitch/audio/bon-appetit.mp3",
    "art": "/private/mio-pitch/images/bon-appetit.webp",
    "reference": "",
    "referenceUrl": ""
  },
  {
    "id": "too-much-fun",
    "title": "Too Much Fun",
    "feeling": "An energetic, Ariana-inspired pop song about girls letting loose and living how they want.",
    "feelingKo": "여자들이 눈치 보지 않고 원하는 대로 즐기는 이야기예요. 아리아나 그란데에서 영감을 받은 에너지 넘치는 팝이에요.",
    "fit": "This feels like it fits in the same flavor profile as “HOTPOT” and “TANGERINE,” playing off that fun vibe.",
    "fitKo": "‘HOTPOT’, ‘TANGERINE’과 비슷한 결의 곡으로, 그 신나는 분위기와 잘 어울려요.",
    "mood": "ENERGETIC POP / 에너지 넘치는 팝",
    "color": "#e1ff45",
    "audio": "/private/mio-pitch/audio/too-much-fun.mp3",
    "art": "/private/mio-pitch/images/too-much-fun.webp",
    "reference": "HOTPOT / TANGERINE",
    "referenceUrl": "https://linktr.ee/miosaysmiao"
  },
  {
    "id": "runaway",
    "title": "Runaway",
    "feeling": "A nostalgic song about wanting to run away with someone because it just feels right.",
    "feelingKo": "이 사람과 함께라면 좋겠다는 확신에, 둘이 어디론가 떠나고 싶어지는 아련한 곡이에요.",
    "fit": "This feels like it fits in the same flavor profile as “TANGERINE”: fresh and emotional, with a bit of that Tyler warmth.",
    "fitKo": "‘TANGERINE’처럼 산뜻하면서도 감정이 담겨 있고, 약간의 Tyler 감성도 느껴지는 곡이에요.",
    "mood": "NOSTALGIC ROMANCE / 아련한 설렘",
    "color": "#8bdbff",
    "audio": "/private/mio-pitch/audio/runaway.mp3",
    "art": "/private/mio-pitch/images/runaway.webp",
    "reference": "TANGERINE",
    "referenceUrl": "https://www.youtube.com/watch?v=yGIlWxROU9U"
  },
  {
    "id": "carousel",
    "title": "Carousel",
    "feeling": "About a relationship that keeps going through the same ups, downs, and patterns.",
    "feelingKo": "좋아졌다가 힘들어졌다가, 같은 패턴을 반복하는 관계에 대한 곡이에요.",
    "fit": "This might fit in the same universe as “TANGERINE” because it’s emotional but energetic. This one is a bit more introspective.",
    "fitKo": "감정이 있으면서도 에너지가 있다는 점에서 ‘TANGERINE’과 같은 분위기에 어울릴 수 있어요. 이 곡은 조금 더 속마음을 들여다보는 편이에요.",
    "mood": "BITTERSWEET LOVE / 씁쓸한 사랑",
    "color": "#a1e7bc",
    "audio": "/private/mio-pitch/audio/carousel.mp3",
    "art": "/private/mio-pitch/images/carousel.webp",
    "reference": "TANGERINE",
    "referenceUrl": "https://www.youtube.com/watch?v=yGIlWxROU9U"
  },
  {
    "id": "bandaid",
    "title": "Bandaid",
    "feeling": "A drum-and-bass track with a tongue-in-cheek take on girls being expected to suck it up when things get hard.",
    "feelingKo": "힘들어도 그냥 참고 버티라는 말을 듣는 여자들의 상황을, 살짝 비꼬는 시선으로 풀어낸 드럼 앤 베이스 곡이에요.",
    "fit": "There isn’t a direct comparison for this one. An emotional R&B vocal over the rhythmic bass could be interesting, and we could tweak the vocal in that direction.",
    "fitKo": "이 곡은 바로 비교할 만한 곡은 없어요. 리듬감 있는 베이스 위에 감정이 담긴 R&B 보컬을 얹으면 재미있을 것 같아요. 보컬을 그런 방향으로 다듬어 볼 수도 있고요.",
    "mood": "DRUM & BASS / 드럼 앤 베이스",
    "color": "#ffa9e5",
    "audio": "/private/mio-pitch/audio/bandaid.mp3",
    "art": "/private/mio-pitch/images/bandaid.webp",
    "reference": "",
    "referenceUrl": ""
  },
  {
    "id": "shoo",
    "title": "SHOO!",
    "feeling": "For the boys who keep coming on to you when you already know you deserve better.",
    "feelingKo": "나는 더 좋은 사람을 만날 수 있다는 걸 아는데도 계속 들이대는 남자들에 대한 곡이에요.",
    "fit": "This feels like it fits in the same flavor profile as “BWB”: R&B with that playful, boys-are-annoying attitude.",
    "fitKo": "‘BWB’처럼 R&B를 바탕으로, 귀찮게 구는 남자들에게 장난스럽게 선을 긋는 느낌이에요.",
    "mood": "PLAYFUL CONFIDENCE / 당당한 장난기",
    "color": "#ff9c59",
    "audio": "/private/mio-pitch/audio/shoo.mp3",
    "art": "/private/mio-pitch/images/shoo.webp",
    "reference": "BWB",
    "referenceUrl": "https://open.spotify.com/track/5E0a9cMznCzsBlTydnka20"
  },
  {
    "id": "hot-take",
    "title": "Hot Take",
    "feeling": "About people who don’t know you having opinions on who you are, just because they see you as an artist or someone in the public eye.",
    "feelingKo": "아티스트이거나 사람들에게 알려져 있다는 이유만으로, 나를 알지도 못하는 사람들이 나에 대해 이렇다 저렇다 말하는 이야기예요.",
    "fit": "This could sit in a similar R&B space to “BWB,” with a different story about being judged from the outside.",
    "fitKo": "‘BWB’와 비슷한 R&B의 결에, 남들이 겉모습만 보고 판단하는 이야기를 담은 곡이에요.",
    "mood": "SPEAK YOUR MIND / 나만의 목소리",
    "color": "#c2a4ff",
    "audio": "/private/mio-pitch/audio/hot-take.mp3",
    "art": "/private/mio-pitch/images/hot-take.webp",
    "reference": "BWB",
    "referenceUrl": "https://open.spotify.com/track/5E0a9cMznCzsBlTydnka20"
  },
  {
    "id": "picky-kitty",
    "title": "Picky Kitty",
    "feeling": "A fun, slightly silly song about being picky because you love yourself enough to know what you want.",
    "feelingKo": "나를 아끼니까 원하는 것도 확실한 거죠. 까다로워도 괜찮다는 이야기를 장난스럽고 엉뚱하게 풀어낸 곡이에요.",
    "fit": "Fresh, futuristic electronic pop. This could be a playful change of pace, with plenty of room for personality.",
    "fitKo": "산뜻하고 미래적인 일렉트로닉 팝이에요. 장난기 있는 분위기로 변화를 주면서, 개성을 마음껏 담아볼 수 있는 곡이에요.",
    "mood": "FUTURE POP / 퓨처 팝",
    "color": "#ff91c8",
    "reference": "",
    "referenceUrl": "",
    "audio": "/private/mio-pitch/audio/picky-kitty.mp3",
    "art": "/private/mio-pitch/images/picky-kitty.webp"
  }
];
